# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OSZToolkit' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

# Pods for OSZToolkit
pod 'AFNetworking', '~> 3.1.0'
pod 'ReactiveObjC', '~> 3.0.0'

end
