# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OSZToolkit' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking', '~> 3.1.0'
  # Pods for OSZToolkit

end
